windowrulev2 = opacity 0.0 0.0,class:^(brave-browser)$

# >>> jcode launch hotkeys (managed) >>>
# jcode: home
bind = SUPER, semicolon, exec, '/home/basant/.jcode/hotkey/launch_jcode_0_cmd_semicolon.sh'
# jcode: last project
bind = SUPER, apostrophe, exec, '/home/basant/.jcode/hotkey/launch_jcode_1_cmd_quote.sh'
# jcode: self-dev
bind = SUPER SHIFT, apostrophe, exec, '/home/basant/.jcode/hotkey/launch_jcode_2_cmd_shift_quote.sh'
# <<< jcode launch hotkeys (managed) <<<
